name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  push:
    branches: [main, master]

jobs:
  semantic-pr:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            style
            refactor
            test
            chore
            ci
          requireScope: false
